"""
This loader can only be used for the .pkl folder generated by conver_iitm_to_pkl.py file from EEG_Speech_Classification repo
"""


import os 
import re
import random
from   collections import defaultdict
from   typing import Dict, List, Optional, Sequence, Set, Tuple
from   dataclasses import dataclass

import numpy as np 
import torch 
import pickle
from   torch.utils.data import Dataset, DataLoader
from   pathlib import Path

FILENAME_RE = re.compile(r"^(?P<listener>[^_]+)_(?P<session>[^_]+)_(?P<audio>[^_.]+)\.pkl$")

@dataclass
class Instance:
    listener_id : str 
    session_id  : str 
    audio_id    : str 
    position    : int 
    label       : str 
    eeg         : np.ndarray


def pad_or_truncate(
    eeg : np.ndarray,
    target_len : int 
):
    T, F = eeg.shape

    if T == target_len : return eeg

    if T > target_len  : return eeg[:T, :]
    if T < target_len  : 
        out = np.zeros((target_len, F), dtype=np.float32)
        out[:T] = eeg

        return out


def load_instances(
    pkl_dir     : Path,
    target_len  : int
) -> List[Instance]:
    instances : List[Instance] = []

    files = sorted(pkl_dir / f for f in os.listdir(pkl_dir) if f.endswith(".pkl"))

    for fname in files:
        with open(fname, "rb") as f:
            d = pickle.load(f)

        listener_id = str(d["listener_id"])
        session_id  = str(d["session_id"])
        audio_id    = str(d["audio_id"])
        eeg_list    = d["eeg_data"]
        labels      = d["label"]


        for pos, (eeg, label) in enumerate(zip(eeg_list, labels)):
            fixed_eeg = pad_or_truncate(eeg, target_len)
            instances.append(
                Instance(
                    listener_id = listener_id,
                    session_id  = session_id,
                    audio_id    = audio_id,
                    position    = pos,
                    label       = str(label),
                    eeg         = fixed_eeg,
                )
            )

    return instances


LabelListenerIndex = Dict[str, Dict[str, List[int]]]

def build_index(
    instances : Sequence[Instance]
) -> LabelListenerIndex:
    index   : LabelListenerIndex = defaultdict(lambda:defaultdict(list))

    for i, inst in enumerate(instances):
        index[inst.label][inst.listener_id].append(i)

    return {
        label : dict(per_listener) for label, per_listener in index.items
    }




